# Generated by Django 4.1 on 2023-04-07 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='studentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('emil', models.EmailField(max_length=100)),
                ('mobile', models.BigIntegerField()),
                ('iname', models.CharField(max_length=50)),
                ('fee', models.IntegerField()),
                ('marks', models.IntegerField()),
                ('location', models.CharField(max_length=50)),
            ],
        ),
    ]
